[colors.primary]
background = '#faf8ff'
foreground = '#191b25'

[colors.selection]
text = '#191b25'
background = '#b8eaff'

[colors.cursor]
text = '#faf8ff'
cursor = '#006780'

[colors.normal]
black   = '#faf8ff'
red     = '#8c0b11'
green   = '#107209'
yellow  = '#7f6f11'
blue    = '#00152b'
magenta = '#0a596c'
cyan    = '#006780'
white   = '#1a1a1a'

[colors.bright]
black   = '#2e2e2e'
red     = '#a52026'
green   = '#1b8c13'
yellow  = '#998721'
blue    = '#007b99'
magenta = '#001b1b'
cyan    = '#598fff'
white   = '#1a1a1a'
